SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `autoecole` ;
CREATE SCHEMA IF NOT EXISTS `autoecole` ;
USE `autoecole` ;

-- -----------------------------------------------------
-- Table `autoecole`.`QUESTIONS_SYNTHESE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`QUESTIONS_SYNTHESE` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`QUESTIONS_SYNTHESE` (
  `ID_QUESTIONS_SYNTHESE` INT(2) NOT NULL ,
  `LIBELLE_QUESTION_SYNTHESE` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_QUESTIONS_SYNTHESE`) );


-- -----------------------------------------------------
-- Table `autoecole`.`CHAMPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`CHAMPS` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`CHAMPS` (
  `ID_ETAT_CHAMPS` SMALLINT(1) NOT NULL ,
  `LIBELLE_ETAT_CHAMPS` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_ETAT_CHAMPS`) );


-- -----------------------------------------------------
-- Table `autoecole`.`FORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`FORMATION` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`FORMATION` (
  `ID_FORMATION` INT(2) NOT NULL ,
  `LIBELLE_FORMATION` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_FORMATION`) );


-- -----------------------------------------------------
-- Table `autoecole`.`MONITEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`MONITEUR` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`MONITEUR` (
  `ID_MONITEUR` INT(2) NOT NULL ,
  `NOM_MONITEUR` CHAR(32) DEFAULT NULL ,
  `PRENOM_MONITEUR` CHAR(32) DEFAULT NULL ,
  PRIMARY KEY (`ID_MONITEUR`) );


-- -----------------------------------------------------
-- Table `autoecole`.`ELEVE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`ELEVE` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`ELEVE` (
  `ID_ELEVE` BIGINT(4) NOT NULL ,
  `ID_FORMATION` INT(2) NOT NULL ,
  `ID_MONITEUR` INT(2) NOT NULL ,
  `NOM_ELEVE` CHAR(32) DEFAULT NULL ,
  `PRENOM_ELEVE` CHAR(32) DEFAULT NULL ,
  `DATE_DE_NAISS_ELEVE` DATE DEFAULT NULL ,
  `MAIL_ELEVE` CHAR(255) DEFAULT NULL ,
  `ADRESSE_ELEVE` CHAR(255) DEFAULT NULL ,
  `CODE_POSTAL_ELEVE` SMALLINT(6) DEFAULT NULL ,
  `COMMUNE_ELEVE` CHAR(32) DEFAULT NULL ,
  `TELEPHONE_ELEVE` CHAR(32) DEFAULT NULL ,
  `PROFESSION_ELEVE` CHAR(32) DEFAULT NULL ,
  `DATE_EVAL_ELEVE` DATE DEFAULT NULL ,
  `RESULTAT_ELEVE_ORAL` INT(2) DEFAULT NULL ,
  `VOLUME_HORAIRE_TH_ELEVE` INT(2) DEFAULT NULL ,
  `VOLUME_HORAIRE_PRATIQUE_ELEVE` INT(2) DEFAULT NULL ,
  `TEST_VU_ELEVE` INT(1) DEFAULT NULL ,
  `OBSERVATION_VUE_ELEVE` CHAR(255) DEFAULT NULL ,
  `DATE_INSCRIPTION_ELEVE` DATE DEFAULT NULL ,
  `DATE_ENREGISTREMENT_ELEVE` DATE DEFAULT NULL ,
  PRIMARY KEY (`ID_ELEVE`) ,
  CONSTRAINT `FK_ELEVE_FORMATION`
    FOREIGN KEY (`ID_FORMATION` )
    REFERENCES `autoecole`.`FORMATION` (`ID_FORMATION` ),
  CONSTRAINT `FK_ELEVE_MONITEUR`
    FOREIGN KEY (`ID_MONITEUR` )
    REFERENCES `autoecole`.`MONITEUR` (`ID_MONITEUR` ));

CREATE INDEX `I_FK_ELEVE_FORMATION` ON `autoecole`.`ELEVE` (`ID_FORMATION` ASC) ;

CREATE INDEX `I_FK_ELEVE_MONITEUR` ON `autoecole`.`ELEVE` (`ID_MONITEUR` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`CATEGORIE_I_O`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`CATEGORIE_I_O` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`CATEGORIE_I_O` (
  `ID_CATEGORIE` SMALLINT(1) NOT NULL ,
  `LIBELLE_CATEGORIE` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_CATEGORIE`) );


-- -----------------------------------------------------
-- Table `autoecole`.`AGENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`AGENDA` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`AGENDA` (
  `DATE_AGENDA` DATE NOT NULL ,
  `HEURE` TIME NOT NULL ,
  PRIMARY KEY (`DATE_AGENDA`, `HEURE`) );


-- -----------------------------------------------------
-- Table `autoecole`.`ETAPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`ETAPE` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`ETAPE` (
  `ID_ETAPE` INT(2) NOT NULL ,
  `LIBELLE_ETAPE` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_ETAPE`) );


-- -----------------------------------------------------
-- Table `autoecole`.`OBJECTIF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`OBJECTIF` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`OBJECTIF` (
  `ID_OBJECTIF` BIGINT(4) NOT NULL ,
  `ID_CATEGORIE` SMALLINT(1) DEFAULT NULL ,
  `ID_ETAPE` INT(2) NOT NULL ,
  `LIBELLE_OBJECTIF` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_OBJECTIF`) ,
  CONSTRAINT `FK_OBJECTIF_CATEGORIE_I_O`
    FOREIGN KEY (`ID_CATEGORIE` )
    REFERENCES `autoecole`.`CATEGORIE_I_O` (`ID_CATEGORIE` ),
  CONSTRAINT `FK_OBJECTIF_ETAPE`
    FOREIGN KEY (`ID_ETAPE` )
    REFERENCES `autoecole`.`ETAPE` (`ID_ETAPE` ));

CREATE INDEX `I_FK_OBJECTIF_CATEGORIE_I_O` ON `autoecole`.`OBJECTIF` (`ID_CATEGORIE` ASC) ;

CREATE INDEX `I_FK_OBJECTIF_ETAPE` ON `autoecole`.`OBJECTIF` (`ID_ETAPE` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`SYNTHESE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`SYNTHESE` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`SYNTHESE` (
  `ID_SYNTHESE` BIGINT(4) NOT NULL ,
  `ID_ETAPE` INT(2) NOT NULL ,
  `LIBELLE_SYNTHESE` CHAR(32) DEFAULT NULL ,
  PRIMARY KEY (`ID_SYNTHESE`) ,
  CONSTRAINT `FK_SYNTHESE_ETAPE`
    FOREIGN KEY (`ID_ETAPE` )
    REFERENCES `autoecole`.`ETAPE` (`ID_ETAPE` ));

CREATE INDEX `I_FK_SYNTHESE_ETAPE` ON `autoecole`.`SYNTHESE` (`ID_ETAPE` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`COMPTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`COMPTE` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`COMPTE` (
  `ID_COMPTE` INT(2) NOT NULL ,
  `ID_COMPTE_UTILISATEUR` BIGINT(4) DEFAULT NULL ,
  `MOT_DE_PASSE_UTILISATEUR` CHAR(32) DEFAULT NULL ,
  PRIMARY KEY (`ID_COMPTE`) );


-- -----------------------------------------------------
-- Table `autoecole`.`REALISER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`REALISER` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`REALISER` (
  `ID_ELEVE` BIGINT(4) NOT NULL ,
  `ID_OBJECTIF` BIGINT(4) NOT NULL ,
  `DATE_REALISATION_OBJECTIF` DATE DEFAULT NULL ,
  `OBSERVATION_OBJECTIF` CHAR(255) DEFAULT NULL ,
  `ETAT_OBJECTIF` SMALLINT(1) DEFAULT NULL ,
  PRIMARY KEY (`ID_ELEVE`, `ID_OBJECTIF`) ,
  CONSTRAINT `FK_REALISER_ELEVE`
    FOREIGN KEY (`ID_ELEVE` )
    REFERENCES `autoecole`.`ELEVE` (`ID_ELEVE` ),
  CONSTRAINT `FK_REALISER_OBJECTIF`
    FOREIGN KEY (`ID_OBJECTIF` )
    REFERENCES `autoecole`.`OBJECTIF` (`ID_OBJECTIF` ));

CREATE INDEX `I_FK_REALISER_ELEVE` ON `autoecole`.`REALISER` (`ID_ELEVE` ASC) ;

CREATE INDEX `I_FK_REALISER_OBJECTIF` ON `autoecole`.`REALISER` (`ID_OBJECTIF` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`SUPERVISER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`SUPERVISER` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`SUPERVISER` (
  `ID_ETAPE` INT(2) NOT NULL ,
  `ID_ELEVE` BIGINT(4) NOT NULL ,
  `DATE_PASSAGE` DATE DEFAULT NULL ,
  `RESULTAT_PASSAGE` TINYINT(1) DEFAULT NULL ,
  `MONITEUR_ID_MONITEUR` INT(2) NOT NULL ,
  PRIMARY KEY (`ID_ETAPE`, `ID_ELEVE`) ,
  CONSTRAINT `FK_SUPERVISER_ETAPE`
    FOREIGN KEY (`ID_ETAPE` )
    REFERENCES `autoecole`.`ETAPE` (`ID_ETAPE` ),
  CONSTRAINT `FK_SUPERVISER_ELEVE`
    FOREIGN KEY (`ID_ELEVE` )
    REFERENCES `autoecole`.`ELEVE` (`ID_ELEVE` ),
  CONSTRAINT `fk_SUPERVISER_MONITEUR1`
    FOREIGN KEY (`MONITEUR_ID_MONITEUR` )
    REFERENCES `autoecole`.`MONITEUR` (`ID_MONITEUR` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `I_FK_SUPERVISER_ETAPE` ON `autoecole`.`SUPERVISER` (`ID_ETAPE` ASC) ;

CREATE INDEX `I_FK_SUPERVISER_ELEVE` ON `autoecole`.`SUPERVISER` (`ID_ELEVE` ASC) ;

CREATE INDEX `fk_SUPERVISER_MONITEUR1` ON `autoecole`.`SUPERVISER` (`MONITEUR_ID_MONITEUR` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`ASSURER_LECON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`ASSURER_LECON` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`ASSURER_LECON` (
  `ID_ELEVE` BIGINT(4) NOT NULL ,
  `ID_MONITEUR` INT(2) NOT NULL ,
  `DATE_AGENDA` DATE NOT NULL ,
  `HEURE` TIME NOT NULL ,
  `NUM_LECON` INT(2) DEFAULT NULL ,
  `DUREE_LECON` INT(2) DEFAULT NULL ,
  `OBSERVATION_LECON` CHAR(255) DEFAULT NULL ,
  PRIMARY KEY (`ID_ELEVE`, `ID_MONITEUR`, `DATE_AGENDA`, `HEURE`) ,
  CONSTRAINT `FK_ASSURER_LECON_ELEVE`
    FOREIGN KEY (`ID_ELEVE` )
    REFERENCES `autoecole`.`ELEVE` (`ID_ELEVE` ),
  CONSTRAINT `FK_ASSURER_LECON_MONITEUR`
    FOREIGN KEY (`ID_MONITEUR` )
    REFERENCES `autoecole`.`MONITEUR` (`ID_MONITEUR` ),
  CONSTRAINT `FK_ASSURER_LECON_AGENDA`
    FOREIGN KEY (`DATE_AGENDA` , `HEURE` )
    REFERENCES `autoecole`.`AGENDA` (`DATE_AGENDA` , `HEURE` ));

CREATE INDEX `I_FK_ASSURER_LECON_ELEVE` ON `autoecole`.`ASSURER_LECON` (`ID_ELEVE` ASC) ;

CREATE INDEX `I_FK_ASSURER_LECON_MONITEUR` ON `autoecole`.`ASSURER_LECON` (`ID_MONITEUR` ASC) ;

CREATE INDEX `I_FK_ASSURER_LECON_AGENDA` ON `autoecole`.`ASSURER_LECON` (`DATE_AGENDA` ASC, `HEURE` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`REPONSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`REPONSE` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`REPONSE` (
  `ID_QUESTIONS_SYNTHESE` INT(2) NOT NULL ,
  `ID_ETAT_CHAMPS` SMALLINT(1) NOT NULL ,
  `ID_SYNTHESE` BIGINT(4) NOT NULL ,
  `ID_ELEVE` BIGINT(4) NOT NULL ,
  `ETAT_REPONSE` TINYINT(1) DEFAULT NULL ,
  PRIMARY KEY (`ID_QUESTIONS_SYNTHESE`, `ID_ETAT_CHAMPS`, `ID_SYNTHESE`, `ID_ELEVE`) ,
  CONSTRAINT `FK_REPONSE_QUESTIONS_SYNTHESE`
    FOREIGN KEY (`ID_QUESTIONS_SYNTHESE` )
    REFERENCES `autoecole`.`QUESTIONS_SYNTHESE` (`ID_QUESTIONS_SYNTHESE` ),
  CONSTRAINT `FK_REPONSE_CHAMPS`
    FOREIGN KEY (`ID_ETAT_CHAMPS` )
    REFERENCES `autoecole`.`CHAMPS` (`ID_ETAT_CHAMPS` ),
  CONSTRAINT `FK_REPONSE_SYNTHESE`
    FOREIGN KEY (`ID_SYNTHESE` )
    REFERENCES `autoecole`.`SYNTHESE` (`ID_SYNTHESE` ),
  CONSTRAINT `FK_REPONSE_ELEVE`
    FOREIGN KEY (`ID_ELEVE` )
    REFERENCES `autoecole`.`ELEVE` (`ID_ELEVE` ));

CREATE INDEX `I_FK_REPONSE_QUESTIONS_SYNTHESE` ON `autoecole`.`REPONSE` (`ID_QUESTIONS_SYNTHESE` ASC) ;

CREATE INDEX `I_FK_REPONSE_CHAMPS` ON `autoecole`.`REPONSE` (`ID_ETAT_CHAMPS` ASC) ;

CREATE INDEX `I_FK_REPONSE_SYNTHESE` ON `autoecole`.`REPONSE` (`ID_SYNTHESE` ASC) ;

CREATE INDEX `I_FK_REPONSE_ELEVE` ON `autoecole`.`REPONSE` (`ID_ELEVE` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`CONTENIR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`CONTENIR` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`CONTENIR` (
  `ID_FORMATION` INT(2) NOT NULL ,
  `ID_ETAPE` INT(2) NOT NULL ,
  PRIMARY KEY (`ID_FORMATION`, `ID_ETAPE`) ,
  CONSTRAINT `FK_CONTENIR_FORMATION`
    FOREIGN KEY (`ID_FORMATION` )
    REFERENCES `autoecole`.`FORMATION` (`ID_FORMATION` ),
  CONSTRAINT `FK_CONTENIR_ETAPE`
    FOREIGN KEY (`ID_ETAPE` )
    REFERENCES `autoecole`.`ETAPE` (`ID_ETAPE` ));

CREATE INDEX `I_FK_CONTENIR_FORMATION` ON `autoecole`.`CONTENIR` (`ID_FORMATION` ASC) ;

CREATE INDEX `I_FK_CONTENIR_ETAPE` ON `autoecole`.`CONTENIR` (`ID_ETAPE` ASC) ;


-- -----------------------------------------------------
-- Table `autoecole`.`PASSER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoecole`.`PASSER` ;

CREATE  TABLE IF NOT EXISTS `autoecole`.`PASSER` (
  `ID_ELEVE` BIGINT(4) NOT NULL ,
  `ID_SYNTHESE` BIGINT(4) NOT NULL ,
  `DATE_PASSAGE_SYNTHESE` DATE DEFAULT NULL ,
  `NB_H_TH` INT(2) DEFAULT NULL ,
  `NB_H_PRATIQUE` INT(2) DEFAULT NULL ,
  `RESULTAT` INT(1) DEFAULT NULL ,
  PRIMARY KEY (`ID_ELEVE`, `ID_SYNTHESE`) ,
  CONSTRAINT `FK_PASSER_ELEVE`
    FOREIGN KEY (`ID_ELEVE` )
    REFERENCES `autoecole`.`ELEVE` (`ID_ELEVE` ),
  CONSTRAINT `FK_PASSER_SYNTHESE`
    FOREIGN KEY (`ID_SYNTHESE` )
    REFERENCES `autoecole`.`SYNTHESE` (`ID_SYNTHESE` ));

CREATE INDEX `I_FK_PASSER_ELEVE` ON `autoecole`.`PASSER` (`ID_ELEVE` ASC) ;

CREATE INDEX `I_FK_PASSER_SYNTHESE` ON `autoecole`.`PASSER` (`ID_SYNTHESE` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
